---
- name: Install Nginx on AWS EC2 Hosts
  hosts: ubuntu_servers
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install nginx
      apt:
        name: nginx
        state: present
